# Generated by Django 4.0.4 on 2022-05-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='documento',
            field=models.IntegerField(),
        ),
    ]
